### ISSUE TITLE
Eyeglass blows up parsing component URIs that start with a forward-slash

### ISSUE THREAD

**Issue by Sam152** [sass-eyeglass/eyeglass#167]
In my case I have a utility called pancake generating root relative sass. Once parsed by eyeglass, this errors out. The offending code looks like:

```
    var match = /^((?:@[^\/]+\/[^\/]+)|(?:[^\/]+))\/?(.*)/.exec(uri);
    var moduleName = match && match[1];


    var relativePath = match && match[2];
    var mod = eyeglass.modules.access(moduleName, isRealFile ? prev : root);

    // for back-compat with previous suggestion @see
    // https://github.com/sass-eyeglass/eyeglass/issues/131#issuecomment-210728946
    // if the module was not found and the name starts with `@`...
    if (!mod && moduleName[0] === "@") {
```

In this code moduleName is null.

And the error it produces looks like:

```
/vagrant/node_modules/sass-versioning/dist/_index.scss
[16:14:31] The following tasks did not complete: default, styles:production, production
[16:14:31] Did you forget to signal async completion?
/vagrant/node_modules/eyeglass/lib/importers/ModuleImporter.js:104
    if (!mod && moduleName[0] === "@") {
                          ^

TypeError: Cannot read property '0' of null
    at Object.<anonymous> (/vagrant/node_modules/eyeglass/lib/importers/ModuleImporter.js:104:27)
    at Object.<anonymous> (/vagrant/node_modules/eyeglass/lib/importers/ImportUtilities.js:24:14)
    at options.importer (/vagrant/node_modules/node-sass/lib/index.js:336:31)
^[[A^C
```

**Comment by eoneill** [comment]
Thanks for reporting. Can you provide an example of the root relative path it generates?

The fix might be as simple as changing
```js
if (!mod && moduleName[0] === "@")
```
to
```js
if (!mod && moduleName && moduleName[0] === "@")
```
