### ISSUE TITLE
Problem with `node-gyp rebuild` during install

### ISSUE THREAD

**Issue by HugoGiraudel** [sass-eyeglass/eyeglass#29]
```sh
node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.10.33 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/Users/administrateur/.nvm/v0.10.33/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/administrateur/Documents/projects/test-eyeglass/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/administrateur/.nvm/v0.10.33/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/administrateur/.node-gyp/0.10.33/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/administrateur/.node-gyp/0.10.33',
gyp info spawn args   '-Dmodule_root_dir=/Users/administrateur/Documents/projects/test-eyeglass/node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: name 'libsass_ext' is not defined while evaluating condition 'libsass_ext == ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/administrateur/.nvm/v0.10.33/lib/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/administrateur/.nvm/v0.10.33/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/administrateur/Documents/projects/test-eyeglass/node-sass
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
```

**Comment by chriseppstein** [comment]
This appears to be a node-sass bug.
